### ISSUE TITLE
https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-on-azure-aks shows 404

### ISSUE THREAD

**Issue by yahonda** [pingcap/docs-tidb-operator#1656]
## Error Report

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?
https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-on-azure-aks shows 404.

2. How would you like to improve it?
https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-on-azure-aks should show "Deploy TiDB on Azure AKS"

**Comment by ran-huang** [comment]
Thanks for reporting! We're investigating the cause of this issue. 
If you need to read the Azure deployment doc, please refer to [1.2 version](https://docs.pingcap.com/tidb-in-kubernetes/v1.2/deploy-on-azure-aks) for now.

**Comment by yahonda** [comment]
Sure.

**Comment by ran-huang** [comment]
[This page](https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-on-azure-aks) is fixed. Thanks!

**Comment by yahonda** [comment]
Thanks for the update. Somehow https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-on-azure-aks  still shows 404.

![Screen Shot 2022-02-16 at 16 55 49](https://user-images.githubusercontent.com/73684/154220556-c84c4005-0d86-4316-afbc-63547395c36a.png)

**Comment by ran-huang** [comment]
That's weird... I'll forward this to the front-end team.

**Comment by ran-huang** [comment]
@yahonda The page should be fixed now. Thanks for reporting the issue. 
Feel free to reach out if you have any other problems. :)

**Comment by yahonda** [comment]
It is working fine now. Thanks!
